import 'dart:async';
import 'dart:ffi';
import 'dart:io';

import 'package:ffi/ffi.dart';
import 'package:unified_game_services_platform_interface/unified_game_services_platform_interface.dart';

import 'eos_bindings.dart';
import 'eos_result.dart';
import 'epic_credentials.dart';

/// Result delivered by an EOS completion callback: the `EOS_EResult` code and,
/// for login, the resolved ProductUserId pointer.
class _CbResult {
  _CbResult(this.code, [this.localUserId]);

  final int code;
  final EOS_ProductUserId? localUserId;
}

/// Epic Online Services provider, backed by the EOS C SDK via dart:ffi.
class EpicProvider extends UnifiedGameServicesPlatform {
  EpicProvider({
    required this.credentials,
    this.libraryPath,
    this.tickInterval = const Duration(milliseconds: 100),
    super.leaderboardIds,
    super.achievementIds,
  });

  final EpicCredentials credentials;
  final String? libraryPath;
  final Duration tickInterval;

  EosBindings? _eos;

  // Handles are already pointers generated by ffigen.
  EOS_HPlatform? _platform;
  EOS_HConnect? _connect;
  EOS_HAchievements? _achievements;
  EOS_HStats? _stats;
  Timer? _pump;
  EOS_ProductUserId? _localUserId;
  String? _puid;

  final StreamController<GameServiceEvent> _events =
  StreamController<GameServiceEvent>.broadcast();

  // --- async bridge ----------------------------------------------------------
  static int _nextToken = 1;
  static final Map<int, Completer<_CbResult>> _pending = {};

  // Specific callbacks required by FFIgen's strict signatures
  static void _onDeviceCreateComplete(Pointer<EOS_Connect_CreateDeviceIdCallbackInfo> info) {
    print('👉 [FFI] Callback _onDeviceCreateComplete disparado!');
    try {
      final tokenPtr = info.ref.ClientData.cast<Int32>();
      final token = tokenPtr.value;
      print('👉 [FFI] Token recuperado: $token');
      final c = _pending.remove(token);
      calloc.free(tokenPtr);

      final dynamic rc = info.ref.ResultCode;
      final int code = rc is int ? rc : rc.value;
      print('👉 [FFI] ResultCode obtenido: $code');
      c?.complete(_CbResult(code));
    } catch (e, stack) {
      print('🔥 [FFI FATAL] Error dentro del callback: $e\n$stack');
    }
  }

  static void _onLoginComplete(Pointer<EOS_Connect_LoginCallbackInfo> info) {
    print('👉 [FFI] Callback _onLoginComplete disparado!');
    try {
      final tokenPtr = info.ref.ClientData.cast<Int32>();
      final token = tokenPtr.value;
      print('👉 [FFI] Token recuperado: $token');
      final c = _pending.remove(token);
      calloc.free(tokenPtr);

      final dynamic rc = info.ref.ResultCode;
      final int code = rc is int ? rc : rc.value;
      print('👉 [FFI] ResultCode obtenido: $code');
      c?.complete(_CbResult(code, info.ref.LocalUserId));
    } catch (e, stack) {
      print('🔥 [FFI FATAL] Error dentro del callback: $e\n$stack');
    }
  }

  static void _onUnlockAchievementsComplete(
      Pointer<EOS_Achievements_OnUnlockAchievementsCompleteCallbackInfo> info,
      ) {
    print('👉 [FFI] Callback _onUnlockAchievementsComplete disparado!');
    try {
      final tokenPtr = info.ref.ClientData.cast<Int32>();
      final token = tokenPtr.value;
      print('👉 [FFI] Token recuperado: $token');
      final c = _pending.remove(token);
      calloc.free(tokenPtr);

      final dynamic rc = info.ref.ResultCode;
      final int code = rc is int ? rc : rc.value;
      print('👉 [FFI] ResultCode obtenido: $code');
      c?.complete(_CbResult(code));
    } catch (e, stack) {
      print('🔥 [FFI FATAL] Error dentro del callback: $e\n$stack');
    }
  }

  static void _onQueryDefinitionsComplete(
      Pointer<EOS_Achievements_OnQueryDefinitionsCompleteCallbackInfo> info,
      ) {
    try {
      final tokenPtr = info.ref.ClientData.cast<Int32>();
      final token    = tokenPtr.value;
      final c        = _pending.remove(token);
      calloc.free(tokenPtr);
      final dynamic rc = info.ref.ResultCode;
      final int code   = rc is int ? rc : rc.value;
      c?.complete(_CbResult(code));
    } catch (e, s) {
      print('🔥 [FFI FATAL] _onQueryDefinitionsComplete: $e\n$s');
    }
  }

  static void _onQueryPlayerAchievementsComplete(
      Pointer<EOS_Achievements_OnQueryPlayerAchievementsCompleteCallbackInfo> info,
      ) {
    try {
      final tokenPtr = info.ref.ClientData.cast<Int32>();
      final token    = tokenPtr.value;
      final c        = _pending.remove(token);
      calloc.free(tokenPtr);
      final dynamic rc = info.ref.ResultCode;
      final int code   = rc is int ? rc : rc.value;
      c?.complete(_CbResult(code));
    } catch (e, s) {
      print('🔥 [FFI FATAL] _onQueryPlayerAchievementsComplete: $e\n$s');
    }
  }

  static void _onIngestStatComplete(
      Pointer<EOS_Stats_IngestStatCompleteCallbackInfo> info,
      ) {
    print('👉 [FFI] Callback _onIngestStatComplete disparado!');
    try {
      final tokenPtr = info.ref.ClientData.cast<Int32>();
      final token = tokenPtr.value;
      print('👉 [FFI] Token recuperado: $token');
      final c = _pending.remove(token);
      calloc.free(tokenPtr);

      final dynamic rc = info.ref.ResultCode;
      final int code = rc is int ? rc : rc.value;
      print('👉 [FFI] ResultCode obtenido: $code');
      c?.complete(_CbResult(code));
    } catch (e, stack) {
      print('🔥 [FFI FATAL] Error dentro del callback: $e\n$stack');
    }
  }

  static void registerWith({
    required EpicCredentials credentials,
    String? libraryPath,
    Map<String, String>? leaderboardIds,
    Map<String, String>? achievementIds,
  }) {
    UnifiedGameServicesPlatform.instance = EpicProvider(
      credentials: credentials,
      libraryPath: libraryPath,
      leaderboardIds: leaderboardIds,
      achievementIds: achievementIds,
    );
  }

  @override
  Set<GameCapability> get capabilities => const {
    GameCapability.achievements,
    GameCapability.leaderboards,
    GameCapability.stats,
  };

  @override
  Stream<GameServiceEvent> get events => _events.stream;

  // --- lifecycle -------------------------------------------------------------
  DynamicLibrary openEosLibrary({String? overridePath}) {
    if (overridePath != null) return DynamicLibrary.open(overridePath);
    final name = Platform.isWindows
        ? 'EOSSDK-Win64-Shipping.dll'
        : Platform.isMacOS
        ? 'libEOSSDK-Mac-Shipping.dylib'
        : 'libEOSSDK-Linux-Shipping.so';
    return DynamicLibrary.open(name);
  }

  static void _onEosLog(Pointer<EOS_LogMessage> msg) {
    final text = msg.ref.Message.cast<Utf8>().toDartString();
    print('🎮 [EOS NATIVE]: $text');
  }

  EosBindings _ensureInit() {
    final existing = _eos;
    if (existing != null) return existing;

    final EosBindings eos;
    try {
      eos = EosBindings(openEosLibrary(overridePath: libraryPath));
    } catch (e) {
      throw SignInFailedException('Failed to load the EOS SDK library.', e);
    }

    final initOpts = calloc<EOS_InitializeOptions>();
    initOpts.ref
      ..ApiVersion = EOS_INITIALIZE_API_LATEST
      ..ProductName = credentials.productName.toNativeUtf8().cast<Char>()
      ..ProductVersion = credentials.productVersion.toNativeUtf8().cast<Char>();
    try {
      final rc = eos.EOS_Initialize(initOpts);
      eos.EOS_Logging_SetLogLevel(
          EOS_ELogCategory.EOS_LC_ALL_CATEGORIES, EOS_ELogLevel.EOS_LOG_Info);
      eos.EOS_Logging_SetCallback(
          Pointer.fromFunction<Void Function(Pointer<EOS_LogMessage>)>(_onEosLog));
      if (rc.value != EosResult.success && rc.value != 15) {
        checkEosResult(rc.value, 'EOS_Initialize');
      }
    } finally {
      calloc.free(initOpts.ref.ProductName);
      calloc.free(initOpts.ref.ProductVersion);
      calloc.free(initOpts);
    }

    final platOpts = calloc<EOS_Platform_Options>();
    platOpts.ref
      ..ApiVersion = EOS_PLATFORM_OPTIONS_API_LATEST
      ..ProductId = credentials.productId.toNativeUtf8().cast<Char>()
      ..SandboxId = credentials.sandboxId.toNativeUtf8().cast<Char>()
      ..DeploymentId = credentials.deploymentId.toNativeUtf8().cast<Char>()
      ..bIsServer = 0; // 0 represents EOS_FALSE

    platOpts.ref.ClientCredentials
      ..ClientId = credentials.clientId.toNativeUtf8().cast<Char>()
      ..ClientSecret = credentials.clientSecret.toNativeUtf8().cast<Char>();

    final key = credentials.encryptionKey;
    if (key != null) {
      platOpts.ref.EncryptionKey = key.toNativeUtf8().cast<Char>();
    }

    try {
      _platform = eos.EOS_Platform_Create(platOpts);
    } finally {
      calloc.free(platOpts.ref.ProductId);
      calloc.free(platOpts.ref.SandboxId);
      calloc.free(platOpts.ref.DeploymentId);
      calloc.free(platOpts.ref.ClientCredentials.ClientId);
      calloc.free(platOpts.ref.ClientCredentials.ClientSecret);
      if (key != null) calloc.free(platOpts.ref.EncryptionKey);
      calloc.free(platOpts);
    }

    if (_platform == null || _platform == nullptr) {
      throw const SignInFailedException(
        'EOS_Platform_Create returned null (check credentials).',
      );
    }

    _connect = eos.EOS_Platform_GetConnectInterface(_platform!);
    print('🔌 [EOS] Connect interface: $_connect');
    _achievements = eos.EOS_Platform_GetAchievementsInterface(_platform!);
    _stats = eos.EOS_Platform_GetStatsInterface(_platform!);

    _eos = eos;
    return eos;
  }

  /// Espera a que el completador se complete, llamando a `EOS_Platform_Tick`
  /// periódicamente para permitir que los callbacks se disparen.
  Future<_CbResult> _track(
      void Function(int token, Pointer<Void> clientData) call,
      {bool treatTimeoutAsSuccess = false}) async {
    final token = _nextToken++;
    final completer = Completer<_CbResult>();
    _pending[token] = completer;

    // Asignar memoria para el token
    final tokenPtr = calloc<Int32>()..value = token;
    final clientData = tokenPtr.cast<Void>();

    // Llamar a la operación
    call(token, clientData);

    // Bucle de ticks hasta que se complete o timeout
    final stopwatch = Stopwatch()..start();
    const timeout = Duration(seconds: 30);
    while (!completer.isCompleted && stopwatch.elapsed < timeout) {
      if (_eos != null && _platform != null) {
        _eos!.EOS_Platform_Tick(_platform!);
      }
      await Future.delayed(const Duration(milliseconds: 50));
    }

    if (!completer.isCompleted) {
      _pending.remove(token);
      calloc.free(tokenPtr);
      if (treatTimeoutAsSuccess) {
        // Para CreateDeviceId, asumimos que el timeout significa que el dispositivo ya existe (código 24)
        print('⚠️ [EOS] Timeout en CreateDeviceId, asumiendo EOS_DuplicateNotAllowed (24)');
        return _CbResult(24); // EOS_DuplicateNotAllowed
      }
      throw const NetworkException('EOS operation timed out.');
    }

    // El callback ya liberó la memoria, así que no liberamos aquí.
    return await completer.future;
  }

  String? _productUserIdToString(EosBindings eos, EOS_ProductUserId? puid) {
    if (puid == null || puid == nullptr) return null;
    final buf = calloc<Char>(33);
    final len = calloc<Int32>()..value = 33;
    try {
      final rc = eos.EOS_ProductUserId_ToString(puid, buf, len);
      if (rc.value != 0) return null;
      return buf.cast<Utf8>().toDartString();
    } finally {
      calloc.free(buf);
      calloc.free(len);
    }
  }

  // --- auth ------------------------------------------------------------------
  @override
  Future<PlayerProfile?> signIn() async {
    print('🔐 [EOS] signIn() called');
    final eos = _ensureInit();
    print('🔐 [EOS] EOS initialized');

    // 1. Ensure a Device ID exists.
    final devOpts = calloc<EOS_Connect_CreateDeviceIdOptions>();
    devOpts.ref
      ..ApiVersion = EOS_CONNECT_CREATEDEVICEID_API_LATEST
      ..DeviceModel = 'unified_game_services'.toNativeUtf8().cast<Char>();
    try {
      print('🔐 [EOS] Calling EOS_Connect_CreateDeviceId...');
      final res = await _track(
            (_, cd) => eos.EOS_Connect_CreateDeviceId(
          _connect!,
          devOpts,
          cd,
          Pointer.fromFunction<
              Void Function(Pointer<EOS_Connect_CreateDeviceIdCallbackInfo>)>(
            _onDeviceCreateComplete,
          ),
        ),
        treatTimeoutAsSuccess: true,
      );
      print('🔐 [EOS] CreateDeviceId result: ${res.code}');
      if (res.code != EosResult.success && res.code != 24) {
        checkEosResult(res.code, 'EOS_Connect_CreateDeviceId');
      }
    } finally {
      calloc.free(devOpts.ref.DeviceModel);
      calloc.free(devOpts);
    }

    // 2. Log in with the Device ID credential.
    final creds = calloc<EOS_Connect_Credentials>();
    creds.ref
      ..ApiVersion = EOS_CONNECT_CREDENTIALS_API_LATEST
      ..Token = nullptr.cast<Char>()
      ..Type = EOS_EExternalCredentialType.EOS_ECT_DEVICEID_ACCESS_TOKEN;

    // Crear UserLoginInfo (necesario para evitar InvalidParameter)
    final userLoginInfo = calloc<EOS_Connect_UserLoginInfo>();
    final displayName = 'Player'.toNativeUtf8();
    userLoginInfo.ref
      ..ApiVersion = EOS_CONNECT_USERLOGININFO_API_LATEST
      ..DisplayName = displayName.cast<Char>();

    final loginOpts = calloc<EOS_Connect_LoginOptions>();
    loginOpts.ref
      ..ApiVersion = EOS_CONNECT_LOGIN_API_LATEST
      ..Credentials = creds
      ..UserLoginInfo = userLoginInfo;

    try {
      print('🔐 [EOS] Calling EOS_Connect_Login...');
      final res = await _track(
            (_, cd) => eos.EOS_Connect_Login(
          _connect!,
          loginOpts,
          cd,
          Pointer.fromFunction<
              Void Function(Pointer<EOS_Connect_LoginCallbackInfo>)>(
            _onLoginComplete,
          ),
        ),
      );
      print('🔐 [EOS] Login result: ${res.code}');
      if (res.code == EosResult.invalidUser) {
        throw const SignInFailedException(
          'EOS_Connect_Login needs EOS_Connect_CreateUser for first-time login.',
        );
      }
      checkEosResult(res.code, 'EOS_Connect_Login');
      _localUserId = res.localUserId;
      _puid = _productUserIdToString(eos, _localUserId);
      print('🔐 [EOS] Logged in as PUID: $_puid');
    } finally {
      calloc.free(creds);
      calloc.free(displayName);
      calloc.free(userLoginInfo);
      calloc.free(loginOpts);
    }

    final profile = _currentProfile();
    if (profile != null) {
      _events.add(UserSignedInEvent(player: profile, timestamp: _now()));
    }
    return profile;
  }

  @override
  Future<void> signOut() async {
    _localUserId = null;
    _puid = null;
    _events.add(UserSignedOutEvent(timestamp: _now()));
  }

  @override
  Future<bool> isSignedIn() async => _puid != null;

  @override
  Future<PlayerProfile?> getCurrentPlayer() async => _currentProfile();

  PlayerProfile? _currentProfile() {
    final id = _puid;
    if (id == null) return null;
    return PlayerProfile(id: id, displayName: id);
  }

  // --- achievements (write path) --------------------------------------------
  @override
  Future<void> unlockAchievement(String achievementId) async {
    final eos = _ensureInit();
    _requireSignedIn();
    final id = resolveAchievementId(achievementId);

    final ids = calloc<Pointer<Char>>(1);
    ids[0] = id.toNativeUtf8().cast<Char>();

    final opts = calloc<EOS_Achievements_UnlockAchievementsOptions>();
    opts.ref
      ..ApiVersion = EOS_ACHIEVEMENTS_UNLOCKACHIEVEMENTS_API_LATEST
      ..UserId = _localUserId!
      ..AchievementIds = ids
      ..AchievementsCount = 1;

    try {
      final res = await _track(
            (_, cd) => eos.EOS_Achievements_UnlockAchievements(
          _achievements!,
          opts,
          cd,
          Pointer.fromFunction<
              Void Function(
                  Pointer<EOS_Achievements_OnUnlockAchievementsCompleteCallbackInfo>,
                  )>(_onUnlockAchievementsComplete),
        ),
      );
      checkEosResult(res.code, 'EOS_Achievements_UnlockAchievements');
    } finally {
      calloc.free(ids[0]);
      calloc.free(ids);
      calloc.free(opts);
    }
  }

  @override
  Future<void> incrementAchievement(String achievementId, int steps) async {
    throw const PlatformOperationException(
      'EOS has no direct incremental-achievement API; ingest the backing stat.',
    );
  }

  @override
  Future<void> revealAchievement(String achievementId) async {
    throw const PlatformOperationException(
      'EOS achievements have no reveal operation.',
    );
  }

  // --- stats + leaderboards (write path) -------------------------------------
  @override
  Future<void> setStat(String key, num value) =>
      _ingest(key, value.toInt(), 'setStat');

  @override
  Future<void> incrementStat(String key, {num by = 1}) =>
      _ingest(key, by.toInt(), 'incrementStat');

  @override
  Future<void> submitScore({
    required String leaderboardId,
    required int score,
  }) async {
    await _ingest(resolveLeaderboardId(leaderboardId), score, 'submitScore');
    _events.add(
      ScoreSubmittedEvent(
        leaderboardId: leaderboardId,
        score: score,
        timestamp: _now(),
      ),
    );
  }

  Future<void> _ingest(String statName, int amount, String op) async {
    final eos = _ensureInit();
    _requireSignedIn();

    final ingest = calloc<EOS_Stats_IngestData>();
    ingest.ref
      ..ApiVersion = EOS_STATS_INGESTDATA_API_LATEST
      ..StatName = statName.toNativeUtf8().cast<Char>()
      ..IngestAmount = amount;

    final opts = calloc<EOS_Stats_IngestStatOptions>();
    opts.ref
      ..ApiVersion = EOS_STATS_INGESTSTAT_API_LATEST
      ..LocalUserId = _localUserId!
      ..Stats = ingest
      ..StatsCount = 1
      ..TargetUserId = _localUserId!;

    try {
      final res = await _track(
            (_, cd) => eos.EOS_Stats_IngestStat(
          _stats!,
          opts,
          cd,
          Pointer.fromFunction<
              Void Function(Pointer<EOS_Stats_IngestStatCompleteCallbackInfo>)>(
            _onIngestStatComplete,
          ),
        ),
      );
      checkEosResult(res.code, 'EOS_Stats_IngestStat ($op)');
    } finally {
      calloc.free(ingest.ref.StatName);
      calloc.free(ingest);
      calloc.free(opts);
    }
  }

  // --- read path -------------------------------------------------------------
  @override
  Future<List<Achievement>> getAchievements() async {
    final eos = _ensureInit();
    _requireSignedIn();

    // ── Paso 1: QueryDefinitions (carga nombres/descripciones en caché local) ──
    final defOpts = calloc<EOS_Achievements_QueryDefinitionsOptions>();
    defOpts.ref
      ..ApiVersion = EOS_ACHIEVEMENTS_QUERYDEFINITIONS_API_LATEST
      ..LocalUserId = _localUserId!
    // EpicUserId es opcional; déjalo en nullptr si no usas Epic Account Services
      ..HiddenAchievementIds_DEPRECATED  = nullptr
      ..HiddenAchievementsCount_DEPRECATED = 0;

    try {
      final res = await _track(
            (_, cd) => eos.EOS_Achievements_QueryDefinitions(
          _achievements!,
          defOpts,
          cd,
          Pointer.fromFunction<
              Void Function(
                  Pointer<EOS_Achievements_OnQueryDefinitionsCompleteCallbackInfo>,
                  )>(_onQueryDefinitionsComplete),
        ),
      );
      checkEosResult(res.code, 'EOS_Achievements_QueryDefinitions');
    } finally {
      calloc.free(defOpts);
    }

    // ── Paso 2: QueryPlayerAchievements (estado desbloqueado/bloqueado) ────────
    final playerOpts = calloc<EOS_Achievements_QueryPlayerAchievementsOptions>();
    playerOpts.ref
      ..ApiVersion    = EOS_ACHIEVEMENTS_QUERYPLAYERACHIEVEMENTS_API_LATEST
      ..LocalUserId   = _localUserId!
      ..TargetUserId  = _localUserId!;

    try {
      final res = await _track(
            (_, cd) => eos.EOS_Achievements_QueryPlayerAchievements(
          _achievements!,
          playerOpts,
          cd,
          Pointer.fromFunction<
              Void Function(
                  Pointer<EOS_Achievements_OnQueryPlayerAchievementsCompleteCallbackInfo>,
                  )>(_onQueryPlayerAchievementsComplete),
        ),
      );
      checkEosResult(res.code, 'EOS_Achievements_QueryPlayerAchievements');
    } finally {
      calloc.free(playerOpts);
    }

    // ── Paso 3: contar cuántos logros hay en caché ────────────────────────────
    final countOpts = calloc<EOS_Achievements_GetPlayerAchievementCountOptions>();
    countOpts.ref
      ..ApiVersion = EOS_ACHIEVEMENTS_GETPLAYERACHIEVEMENTCOUNT_API_LATEST
      ..UserId     = _localUserId!;
    final count = eos.EOS_Achievements_GetPlayerAchievementCount(
        _achievements!, countOpts);
    calloc.free(countOpts);

    print('🏆 [EOS] Player achievement count: $count');

    // ── Paso 4: copiar cada logro y mapear al modelo de la plataforma ─────────
    final results = <Achievement>[];

    for (int i = 0; i < count; i++) {
      final copyOpts =
      calloc<EOS_Achievements_CopyPlayerAchievementByIndexOptions>();
      copyOpts.ref
        ..ApiVersion      = EOS_ACHIEVEMENTS_COPYPLAYERACHIEVEMENTBYINDEX_API_LATEST
        ..LocalUserId     = _localUserId!
        ..TargetUserId    = _localUserId!
        ..AchievementIndex = i;

      final outPtr =
      calloc<Pointer<EOS_Achievements_PlayerAchievement>>();

      try {
        final dynamic rc = eos.EOS_Achievements_CopyPlayerAchievementByIndex(
          _achievements!,
          copyOpts,
          outPtr,
        );
        final int code = rc is int ? rc : rc.value;

        if (code == EosResult.success) {
          final a = outPtr.value.ref;

          // EOS_ACHIEVEMENTS_ACHIEVEMENT_UNLOCKTIME_UNDEFINED == -1
          const int kUndefined = -1;
          final isUnlocked = a.UnlockTime != kUndefined;

          final id = a.AchievementId == nullptr
              ? 'achievement_$i'
              : a.AchievementId.cast<Utf8>().toDartString();

          final name = a.DisplayName == nullptr
              ? id
              : a.DisplayName.cast<Utf8>().toDartString();

          final desc = a.Description == nullptr
              ? null
              : a.Description.cast<Utf8>().toDartString();

          final iconUrl = a.IconURL == nullptr
          ? null
          : a.IconURL.cast<Utf8>().toDartString();

          final unlockedAt = isUnlocked
              ? DateTime.fromMillisecondsSinceEpoch(a.UnlockTime * 1000, isUtc: true)
              : null;

          results.add(Achievement(
            id: id,
            title: name,
            description: desc,
            iconUrl: iconUrl,
            isUnlocked: isUnlocked,
            unlockedAt: unlockedAt
          ));

          // ⚠️ Obligatorio: libera la copia alocada por el SDK
          eos.EOS_Achievements_PlayerAchievement_Release(outPtr.value);
        } else {
          print('⚠️ [EOS] CopyPlayerAchievementByIndex[$i] result: $code');
        }
      } finally {
        calloc.free(copyOpts);
        calloc.free(outPtr);
      }
    }

    return results;
  }

  @override
  Future<List<Stat>> getStats() => _readGap('getStats');

  @override
  Future<Stat?> getStat(String key) => _readGap('getStat');

  @override
  Future<Leaderboard> getLeaderboard(
      String leaderboardId, {
        LeaderboardTimeScope timeScope = LeaderboardTimeScope.allTime,
        LeaderboardCollection collection = LeaderboardCollection.global,
        int maxResults = 25,
      }) =>
      _readGap('getLeaderboard');

  @override
  Future<LeaderboardEntry?> getPlayerScore(
      String leaderboardId, {
        LeaderboardTimeScope timeScope = LeaderboardTimeScope.allTime,
      }) =>
      _readGap('getPlayerScore');

  Future<Never> _readGap(String op) async => throw PlatformOperationException(
    'EOS $op (read path) is not implemented in the hand-authored bindings.',
  );

  void _requireSignedIn() {
    if (_puid == null) throw const NotSignedInException();
  }

  DateTime _now() => DateTime.now();

  Future<void> dispose() async {
    _pump?.cancel();
    _pump = null;
    final eos = _eos;
    if (eos != null && _platform != null) {
      eos.EOS_Platform_Release(_platform!);
      eos.EOS_Shutdown();
    }
    _platform = null;
    _eos = null;
    _puid = null;
    await _events.close();
  }
}